# Generated by Django 4.2.4 on 2023-08-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poema',
            name='exceto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
