# Generated by Django 4.2.4 on 2023-08-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_poema_exceto'),
    ]

    operations = [
        migrations.AddField(
            model_name='poema',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
